version: "3.8"
services:
  traefik:
    image: "traefik:latest"
    networks:
      - traefik_reseau
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # Pour Docker pour Windows c'est double slash au lieu d'un seul
      - "//var/run/docker.sock:/var/run/docker.sock:ro"
      # Ici : fichier de config partagé
      - "./config:/etc/traefik"
 
  whoami_1:
    image: "containous/whoami"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - traefik_reseau
  whoami_2:
    image: "containous/whoami"
    container_name: "whoami_2"
    networks:
      - traefik_reseau

networks:
  traefik_reseau:
    driver: bridge