http:
  routers:
    api:
      entryPoints:
        - "web"
      rule: "Host(`localhost`)"
      service: api@internal
    whoami_1:
      entryPoints:
        - "web"
      rule: "Host(`first.localhost`)"
      service: whoami-1-traefik-docker@docker
    whoami_2:
      entryPoints:
        - "web"
      rule: "Host(`second.localhost`)"
      service: whoami-2-traefik-docker@docker


