providers:
  docker: {}
  file:
    directory: "/etc/traefik"
    filename: "dynamic.yml"
    watch: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  # websecure:
  #   address: ":443"

# certificatesResolvers:
#   montlschallenge:
#     acme:
#       email:  "xianledatascientist@unmondesansxian.fr"
#       storage:  "/letsencrypt/acme.json"
#       tlsChallenge: {}

api:
  dashboard: true
  insecure: true